# NUMPY

ini kan array biasa

In [28]:
mylist = [1,2,3]

In [29]:
type(mylist)

list

tapi bisa di ubah jadi array numpy, caranya gini

In [30]:
import numpy as np

In [31]:
np.__version__

'1.20.1'

In [32]:
myarr = np.array(mylist)

In [33]:
myarr

array([1, 2, 3])

In [34]:
type(myarr)

numpy.ndarray

kita coba bikin matrix pake list biasa

In [35]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [36]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

kalo pake numpy, dia tau ini itu 2 dimensional, jadi ada row column nya

In [37]:

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

beberapa built in function numpy, pencet shift+tab buat more info buat functionnya!

In [38]:
np.arange(0,10) # artinya buat array dari 0 - up to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(0,101,2) # dari 0 - upto 101 step 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [40]:
np.zeros(5) # floating point number

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

buat linspace, banyak orang suka bingung penggunaannya karena mirip np.arange. syntaxnya agak beda
kalo linspace (start, stop(biasa upto, kalo ini termasuk), num(num ini mau di bagi spacenya brp))
jadi basically ini linearly divide angkanya secara sama rata, contoh liat dibawah aja

In [43]:
np.linspace(0,10,3) # artinya dari 0 - 10 di bagi rata buat output 3 angka

array([ 0.,  5., 10.])

In [44]:
np.linspace(0,10,11) # kadang orang bingung knp num nya 11 ga 10 aja, karena ini termasuk 10 nya, jadi 0-10 ada 11 angka

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
len(np.linspace(0,10,11)) # ada 11 num

11

identity matrix, yang 1 nya diagonal di square matrix

In [46]:
np.eye(5) # karena pasti square, jadi input aja mau berapa kali berapa

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.random.rand(1) # angkanya pasti antara 0-1

array([0.01665562])

In [48]:
np.random.rand(5,3)

array([[0.60640979, 0.38279741, 0.51058846],
       [0.48162278, 0.18774189, 0.9264689 ],
       [0.69287849, 0.3963307 , 0.13786258],
       [0.54471284, 0.83779708, 0.51147576],
       [0.92156686, 0.12046827, 0.02881545]])

yang tadi itu NORMAL DISTRIBUTION. kalo mau pake STANDARD NORMAL DISTRIBUTION kayak gini

In [49]:
np.random.randn(10) # cara pakenya sama, tapi ini bisa negative

array([-1.01638912,  1.22066015,  0.45315463, -1.36154971, -0.30647528,
       -1.07532442, -0.24969248,  0.57374526,  0.97741774, -0.8430306 ])

In [50]:
np.random.randn(2,3) # angka yg leih bakalan muncul adalah angka yang lebih dekat sama 0

array([[ 1.62503857, -0.60386225, -0.52843557],
       [-0.16663027,  1.15367619,  1.51148047]])

In [51]:
np.random.randint(0,101,5) # dari 0 sampe upto 101, 5 angka. randint itu cuma int bukan float

array([35, 25, 48, 96, 92])

In [52]:
np.random.randint(0,101,(4,5)) # bisa juga dimensional

array([[98, 27, 29, 79, 82],
       [20, 46, 83, 96, 58],
       [75, 32, 39,  1, 22],
       [63, 54, 66, 97, 14]])

yang next ini penting banget dan bakal sering dipake. namanya SEED, ini gunanya untuk ngesave random number yg udah di generate biar bisa dipake lagi. jadi saat kita mau test beberapa model, biar akurat pake random number yang sama biar hasilnya lebih akurat. contoh

In [53]:
np.random.seed(18) # 18 ini buat sendiri, jadi kayak kasih code '18' ke angka2 ini
np.random.rand(5) # generate 5 random number 0-1

array([0.65037424, 0.50545337, 0.87860147, 0.18184023, 0.85223307])

In [54]:
np.random.seed(17) # coba kita kasih kode '17'
np.random.rand(5)

array([0.294665  , 0.53058676, 0.19152079, 0.06790036, 0.78698546])

In [55]:
np.random.seed(18) # coba kita call seed 18
np.random.rand(5)

array([0.65037424, 0.50545337, 0.87860147, 0.18184023, 0.85223307])

hasil nya sama, jadi setiap pake seed 18 pasti angkanya itu terus, sama juga kaya 17

In [56]:
np.random.seed(17)
np.random.rand(5)

array([0.294665  , 0.53058676, 0.19152079, 0.06790036, 0.78698546])

In [57]:
np.random.seed(17)
np.random.rand(3)

array([0.294665  , 0.53058676, 0.19152079])

kalo ga pake seed angkanya jadi totally random lagi

In [58]:
np.random.rand(4)

array([0.06790036, 0.78698546, 0.65633352, 0.6375209 ])

In [59]:
xx = np.arange(0,25)

In [60]:
xx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
xx.reshape(5,5) # function buat reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

reshape nya harus muat, kalo misal datanya 25 berarti harus 5x5, kalo ga muat error

In [62]:
xx.reshape(4,4) # gamuat

ValueError: cannot reshape array of size 25 into shape (4,4)

coba kita buat random array

In [63]:
ranarr = np.random.randint(0,101,10)

In [64]:
ranarr

array([ 7,  1, 17, 41, 56, 10, 98,  3, 63,  6])

In [65]:
ranarr.max() # buat cari angka paling gede

98

In [66]:
ranarr.min() # buat cari angka paling kecil

1

In [67]:
ranarr.argmax() # buat cari index location max nya

6

In [68]:
ranarr.argmin() # buat cari index location min nya

1

In [69]:
ranarr.dtype # buat liat data typenya

dtype('int32')

In [70]:
ranarr.shape # buat liat shapenya

(10,)

kenapa (10,) ada comma nya? artinya ini bukan dimensional berarti cuma bukan 10,1 maksudnya. kalo 10,1 kan memanjang kebawah

In [71]:
arrx = ranarr.reshape(5,2)

In [72]:
arrx

array([[ 7,  1],
       [17, 41],
       [56, 10],
       [98,  3],
       [63,  6]])

In [73]:
arrx.shape

(5, 2)

indexing and selection

In [74]:
arr = np.arange(0,11)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr[8] # ambil value dari index 8

8

In [77]:
arr[1:5] # ambil value index 1 - upto 5

array([1, 2, 3, 4])

In [78]:
arr[0:5] # 0 - upto 5

array([0, 1, 2, 3, 4])

In [79]:
arr[:5] # atau kaya gini

array([0, 1, 2, 3, 4])

In [80]:
arr[5:] # dan sebaliknya

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr = np.arange(0,11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
slice_of_arr = arr[0:6] # kita coba slice

In [84]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [85]:
slice_of_arr[:] = 99 # coba kita ubah valuenya (broadcasting)

In [86]:
slice_of_arr # valuenya bakal keubah juga di original arraynya

array([99, 99, 99, 99, 99, 99])

In [87]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
arr = np.arange(0,11)

In [89]:
# kalo mau ga keubah harus explicit pake copy()
arr_copy = arr.copy()

In [90]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [92]:
arr_2d # matrix 3x3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [93]:
arr_2d.shape

(3, 3)

inget buat slicing!!!
arr[row][col]

In [94]:
# indexing row nya
arr_2d[1] # ambil row 1

array([20, 25, 30])

In [95]:
# ambil individual element value nya
arr_2d[1][0]

20

In [96]:
# bisa juga gini
arr_2d[1,0]

20

In [97]:
# slice matrixnya
# ambil 2x2 kanan atas
arr_2d[:2,1:] # row semua - upto 2, 1 - semua

array([[10, 15],
       [25, 30]])

In [98]:
import numpy as np

In [99]:
arr = np.arange(1,11)

In [100]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr > 3 # bisa buat condition

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [102]:
bool_arr = arr > 3 # masukin ke variable

In [103]:
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [104]:
arr[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [105]:
# cara cepetnya sebenernya gini, gausah tampung ke variable
# langsung condition nya aja
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

Operations

In [106]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
# kita bisa +-/* array
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [108]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [109]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [110]:
arr / arr

<ipython-input-110-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

disini bakalan ada warning karena division by 0, tapi bukan error

In [111]:
1/arr # ada hasil infinite karena 1/0 itu infinite

<ipython-input-111-8ed13a59b8f3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr # ada hasil infinite karena 1/0 itu infinite


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

ini sebenernya berbahaya karena numpy bakalan tetep run soalnya ga ada error, jadi harus di perhatiin warning nya

In [112]:
arr**3 # semua value array di pangkat 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

### Universal Array Function
ini ada banyak tapi contoh yang penting aja

In [113]:
np.sqrt(arr) # square root atau akar

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [119]:
np.exp(arr) # ngitung exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [120]:
np.sin(arr) # trigonometri cos tan juga bisa

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [122]:
np.log(arr) # logaritma

<ipython-input-122-021441d1ebac>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # logaritma


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

### Summmary Statistics on Arrays
ini lebih penting buat statistik data dll

In [123]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
arr.sum()

45

In [125]:
arr.mean()

4.5

In [126]:
arr.max()

9

In [127]:
arr.min()

0

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

<strong>Sekarang tentang Axis Penting</strong>

In [117]:
# kita buat matrix 3x4
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
arr_2d.shape # hasilnya pasti tuple (0,1)

(3, 4)

shape array itu terdiri dari axis 0 = row, dan axis 1 = column

jadi kalo mau sum, kata kuncinya itu arross, mau across row atau column, habis itu ganti axis nya sesuai yg kita mau

In [129]:
arr_2d.sum(axis=0) # dia bakalan jumlahin semua rownya (vertical)

array([15, 18, 21, 24])

In [130]:
arr_2d.sum(axis=1) # dia bakalan jumlahin semua column (horizontal)

array([10, 26, 42])