In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [3]:
b = np.array([5,6,7,8])
print (b)

[5 6 7 8]


In [4]:
c = np.array([[1,2,3,4],[5,6,7,8,],[7,8,9,10]])
print (c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]


In [5]:
a = np.arange(0,1,0.1)
print (a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [6]:
b = np.linspace(0,1,10)
print (b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [7]:
c = np.linspace(0,1,10,endpoint = False)
print (c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [8]:
d = np.logspace(0,2,5)
print (d)

[  1.           3.16227766  10.          31.6227766  100.        ]


In [9]:
def func(i):
    return i % 4 + 1

In [10]:
np.fromfunction(func,(10,))

array([1., 2., 3., 4., 1., 2., 3., 4., 1., 2.])

In [11]:
a = np.array([1,2,3,4], dtype=float)
print (a)

[1. 2. 3. 4.]


In [12]:
a.dtype

dtype('float64')

In [13]:
c = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
c.shape

(3, 4)

In [14]:
a = np.array([1,2,3,4])
d = a.reshape((2,2))
print (d)

[[1 2]
 [3 4]]


In [15]:
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
a = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
print (a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [17]:
persontype = np.dtype({
'names':['name','age','weight'],
'formats':['S30','i','f']})

In [18]:
a = np.array([("Zhang", 32, 75.5), ("Wang", 24, 65.2)], 
      dtype=persontype) 
print (a[0])

(b'Zhang', 32, 75.5)


In [19]:
x = np.linspace(0, 2*np.pi, 10)
y = np.sin(x)
print (y)

[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [20]:
a = np.arange(0, 4)
b = np.arange(1, 5)
np.add(a, b)

array([1, 3, 5, 7])

In [21]:
a+b

array([1, 3, 5, 7])

In [22]:
np.array([1, 2, 3]) < np.array([3, 2, 1])

array([ True, False, False])

In [23]:
def num_judge(x, a):
        if x%3 == 0:
            r = 0
        elif x%5 == 0:
            r = 0
        else:
            r = a
        return r

In [24]:
x = np.linspace(0, 10, 11)
y = np.array([num_judge(t, 2) for t in x])
print (y)

[0 2 2 0 2 0 0 2 2 0 0]


In [25]:
numb_judge = np.frompyfunc(num_judge, 2, 1)

In [26]:
y = numb_judge(x,2)
print (y)

[0 2 2 0 2 0 0 2 2 0 0]


In [27]:
y.astype(np.int)

array([0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 0])

In [28]:
a = np.arange(0, 60, 10).reshape(-1, 1)
b = np.arange(0, 5)
c = a+b
print (c)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]


In [29]:
print (c.shape)

(6, 5)


In [30]:
x, y = np.ogrid[:5, :5]

In [31]:
print(x)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [32]:
print(y)

[[0 1 2 3 4]]


In [33]:
from numpy import random as nr
np.set_printoptions(precision=2)

In [34]:
r1 = nr.rand(4, 3)
print (r1)

[[0.15 0.83 0.16]
 [0.81 0.55 0.86]
 [0.54 0.32 0.69]
 [0.57 0.65 0.92]]


In [35]:
r2 = nr.poisson(2.0, (4, 3))
print (r2)

[[4 1 3]
 [1 3 4]
 [1 1 4]
 [2 0 2]]


In [36]:
np.random.seed(42)
a = np.random.randint(0,10,size=(4,5))

In [37]:
np.sum(a)

96

In [38]:
a

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1]])

In [39]:
np.sum(a, axis=1)

array([26, 28, 24, 18])

In [40]:
np.sum(a, axis=0)  

array([22, 13, 27, 18, 16])

In [41]:
np.sum(a,1,keepdims=True)

array([[26],
       [28],
       [24],
       [18]])

In [42]:
np.sum(a,0,keepdims=True)

array([[22, 13, 27, 18, 16]])

In [43]:
a = np.array([1, 3, 5, 7])
b = np.array([2, 4, 6])
np.maximum(a[None, :], b[:, None])

array([[2, 3, 5, 7],
       [4, 4, 5, 7],
       [6, 6, 6, 7]])

In [44]:
print(np.sort(a))

[1 3 5 7]


In [45]:
np.sort(a, axis=0)

array([1, 3, 5, 7])

In [46]:
r = np.abs(np.random.randn(100000))
np.percentile(r, [68.3, 95.4, 99.7])

array([1.  , 2.  , 2.96])

In [47]:
np.random.seed(42)
a = np.random.randint(0, 8, 10)
np.unique(a)

array([1, 2, 3, 4, 6, 7])

In [48]:
a

array([6, 3, 4, 6, 2, 7, 4, 4, 6, 1])

In [50]:
x, index=np.unique(a, return_index=True)

In [51]:
x

array([1, 2, 3, 4, 6, 7])

In [52]:
index

array([9, 4, 1, 2, 0, 5], dtype=int64)

In [53]:
a[index]

array([1, 2, 3, 4, 6, 7])

In [54]:
x, rindex = np.unique(a, return_inverse=True)

In [55]:
rindex

array([4, 2, 3, 4, 1, 5, 3, 3, 4, 0], dtype=int64)

In [56]:
x[rindex]

array([6, 3, 4, 6, 2, 7, 4, 4, 6, 1])

In [58]:
a = np.array([6,3,4,6,2,7,4,4,6,1])
np.bincount(a)

array([0, 1, 1, 1, 3, 0, 3, 1], dtype=int64)

In [59]:
x = np.array([0,1,2,2,1,1,0])
w = np.array([0.1,0.3,0.2,0.4,0.5,0.8,1.2])
np.bincount(x,w)

array([1.3, 1.6, 0.6])

In [60]:
a = np.random.rand(100)
np.histogram(a, bins=5, range=(0,1))

(array([28, 18, 17, 19, 18], dtype=int64),
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. ]))

In [61]:
np.histogram(a, bins=[0,0.4,0.8,1.0])

(array([46, 36, 18], dtype=int64), array([0. , 0.4, 0.8, 1. ]))

In [66]:
a = np.arange(3)
b = np.arange(10,13)
v = np.vstack((a,b))
h = np.hstack((a,b))
c = np.column_stack((a,b))

In [67]:
v

array([[ 0,  1,  2],
       [10, 11, 12]])

In [68]:
h

array([ 0,  1,  2, 10, 11, 12])

In [69]:
c

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12]])

In [73]:
a = np.array([6,3,7,4,6,9,2,6,7,4,3,7])
b = np.array([1,3,6,9,10])
np.split(a, b)

[array([6]),
 array([3, 7]),
 array([4, 6, 9]),
 array([2, 6, 7]),
 array([4]),
 array([3, 7])]

In [74]:
np.split(a,2)

[array([6, 3, 7, 4, 6, 9]), array([2, 6, 7, 4, 3, 7])]

In [76]:
a = np.array([1.0,0,-2,1])
p = np.poly1d(a)
print (p)

   3
1 x - 2 x + 1


In [77]:
p(np.linspace(0,1,5))

array([ 1.  ,  0.52,  0.12, -0.08,  0.  ])

In [78]:
p + [-2, 1]

poly1d([ 1.,  0., -4.,  2.])

In [79]:
p*p

poly1d([ 1.,  0., -4.,  2.,  4., -4.,  1.])

In [80]:
p/[1,1]

(poly1d([ 1., -1., -1.]), poly1d([2.]))

In [81]:
p.deriv()

poly1d([ 3.,  0., -2.])

In [82]:
p.integ()

poly1d([ 0.25,  0.  , -1.  ,  1.  ,  0.  ])

In [83]:
r = np.roots(p)
r

array([-1.62,  1.  ,  0.62])