NUMPY

ini kan array biasa

In [1]:
mylist = [1,2,3]

In [2]:
type(mylist)

list

tapi bisa di ubah jadi array numpy, caranya gini

In [3]:
import numpy as np

In [4]:
np.__version__

'1.20.1'

In [5]:
myarr = np.array(mylist)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

kita coba bikin matrix pake list biasa

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

kalo pake numpy, dia tau ini itu 2 dimensional, jadi ada row column nya

In [11]:

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

beberapa built in function numpy, pencet shift+tab buat more info buat functionnya!

In [13]:
np.arange(0,10) # artinya buat array dari 0 - up to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,101,2) # dari 0 - upto 101 step 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
np.zeros(5) # floating point number

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

buat linspace, banyak orang suka bingung penggunaannya karena mirip np.arange. syntaxnya agak beda
kalo linspace (start, stop(biasa upto, kalo ini termasuk), num(num ini mau di bagi spacenya brp))
jadi basically ini linearly divide angkanya secara sama rata, contoh liat dibawah aja

In [21]:
np.linspace(0,10,3) # artinya dari 0 - 10 di bagi rata buat output 3 angka

array([ 0.,  5., 10.])

In [23]:
np.linspace(0,10,11) # kadang orang bingung knp num nya 11 ga 10 aja, karena ini termasuk 10 nya, jadi 0-10 ada 11 angka

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
len(np.linspace(0,10,11)) # ada 11 num

11

identity matrix, yang 1 nya diagonal di square matrix

In [27]:
np.eye(5) # karena pasti square, jadi input aja mau berapa kali berapa

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(1) # angkanya pasti antara 0-1

array([0.24261021])

In [29]:
np.random.rand(5,3)

array([[0.8957683 , 0.3402554 , 0.06311747],
       [0.9088164 , 0.79201981, 0.49305221],
       [0.37714739, 0.16329858, 0.0894461 ],
       [0.40243176, 0.56687713, 0.31760154],
       [0.05784264, 0.6041936 , 0.06245778]])

yang tadi itu NORMAL DISTRIBUTION. kalo mau pake STANDARD NORMAL DISTRIBUTION kayak gini

In [31]:
np.random.randn(10) # cara pakenya sama, tapi ini bisa negative

array([-0.31106952, -0.52042589,  1.48826409, -1.38167632,  0.82275083,
       -1.15618293, -0.88021606, -0.56058143, -0.08142017,  0.91267321])

In [33]:
np.random.randn(2,3) # angka yg leih bakalan muncul adalah angka yang lebih dekat sama 0

array([[ 0.55850848, -1.66435559,  0.95434952],
       [-0.3185887 ,  1.2126898 ,  2.46756539]])

In [34]:
np.random.randint(0,101,5) # dari 0 sampe upto 101, 5 angka. randint itu cuma int bukan float

array([42, 48, 35, 32, 68])

In [35]:
np.random.randint(0,101,(4,5)) # bisa juga dimensional

array([[53, 11, 85,  3, 14],
       [85, 41, 48, 28, 26],
       [58, 56, 51, 88, 18],
       [25, 13, 43, 85, 45]])

yang next ini penting banget dan bakal sering dipake. namanya SEED, ini gunanya untuk ngesave random number yg udah di generate biar bisa dipake lagi. jadi saat kita mau test beberapa model, biar akurat pake random number yang sama biar hasilnya lebih akurat. contoh

In [37]:
np.random.seed(18) # 18 ini buat sendiri, jadi kayak kasih code '18' ke angka2 ini
np.random.rand(5) # generate 5 random number 0-1

array([0.65037424, 0.50545337, 0.87860147, 0.18184023, 0.85223307])

In [39]:
np.random.seed(17) # coba kita kasih kode '17'
np.random.rand(5)

array([0.294665  , 0.53058676, 0.19152079, 0.06790036, 0.78698546])

In [40]:
np.random.seed(18) # coba kita call seed 18
np.random.rand(5)

array([0.65037424, 0.50545337, 0.87860147, 0.18184023, 0.85223307])

hasil nya sama, jadi setiap pake seed 18 pasti angkanya itu terus, sama juga kaya 17

In [41]:
np.random.seed(17)
np.random.rand(5)

array([0.294665  , 0.53058676, 0.19152079, 0.06790036, 0.78698546])

In [42]:
np.random.seed(17)
np.random.rand(3)

array([0.294665  , 0.53058676, 0.19152079])

kalo ga pake seed angkanya jadi totally random lagi

In [43]:
np.random.rand(4)

array([0.06790036, 0.78698546, 0.65633352, 0.6375209 ])

In [44]:
xx = np.arange(0,25)

In [45]:
xx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
xx.reshape(5,5) # function buat reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

reshape nya harus muat, kalo misal datanya 25 berarti harus 5x5, kalo ga muat error

In [47]:
xx.reshape(4,4) # gamuat

ValueError: cannot reshape array of size 25 into shape (4,4)

coba kita buat random array

In [50]:
ranarr = np.random.randint(0,101,10)

In [51]:
ranarr

array([ 1, 17, 41, 56, 10, 98,  3, 63,  6, 91])

In [53]:
ranarr.max() # buat cari angka paling gede

98

In [54]:
ranarr.min() # buat cari angka paling kecil

1

In [55]:
ranarr.argmax() # buat cari index location max nya

5

In [56]:
ranarr.argmin() # buat cari index location min nya

0

In [58]:
ranarr.dtype # buat liat data typenya

dtype('int32')

In [59]:
ranarr.shape # buat liat shapenya

(10,)

kenapa (10,) ada comma nya? artinya ini bukan dimensional berarti cuma bukan 10,1 maksudnya. kalo 10,1 kan memanjang kebawah

In [60]:
arrx = ranarr.reshape(5,2)

In [61]:
arrx

array([[ 1, 17],
       [41, 56],
       [10, 98],
       [ 3, 63],
       [ 6, 91]])

In [62]:
arrx.shape

(5, 2)